name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '20.11.1'
          cache: 'pnpm' # Cache pnpm packages

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install
        run: |
          pnpm install --frozen-lockfile          
          pnpm run build:all

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/demo-wp/public
          branch: gh-pages
